apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qtodo.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qtodo.postgresqlLabels" . | nindent 4 }}
spec:
  serviceName: {{ include "qtodo.postgresql.serviceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "qtodo.postgresqlSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qtodo.postgresqlSelectorLabels" . | nindent 8 }}
      {{- with .Values.postgresql.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.postgresql.create }}
      serviceAccountName: {{ include "qtodo.postgresqlServiceAccountName" . }}
      {{- end }}
      containers:
        - name: postgresql
          image: "{{ include "qtodo.images.image" .Values.postgresql.image }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.service.targetPort }}
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "qtodo.fullname" . }}-postgresql
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qtodo.fullname" . }}-postgresql
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "qtodo.fullname" . }}-postgresql
                  key: POSTGRESQL_DATABASE
          {{- with .Values.postgresql.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgresql.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: postgresql-data
              mountPath: {{ .Values.postgresql.persistence.mountPath }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes:
          - {{ .Values.postgresql.persistence.accessMode }}
        {{- if .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
