apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qtodo.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qtodo.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRESQL_USER: {{ .Values.postgresql.database.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.database.password | b64enc }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database.name | b64enc }}
