{{- if .Values.serviceAccount.qtodo.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qtodo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qtodo.qtodoLabels" . | nindent 4 }}
  {{- with .Values.serviceAccount.qtodo.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
