{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "qtodo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qtodo.qtodoLabels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ include "qtodo.fullname" . }}-qtodo
    weight: 100
  port:
    targetPort: {{ printf "%s-tcp" (include "qtodo.app.port" .) }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
